x-uffizzi:
  ingress:
    service: tidaldl
    port: 80
services:
  tidaldl:
    image: tidaldl:latest
    build: .
    environment:
      TG_BOT_TOKEN: ""
      APP_ID: ""
      API_HASH: ""
      AUTH_CHAT: ""
      ADMINS: "2024984460"
      ALLOW_DUMP: "True"
      SEARCH_CHANNEL: ""
      IS_BOT_PUBLIC: "True"
      TIDAL_REGION: "IN"
      BOT_USERNAME: ""
      OWNER_USERNAME: ""
      DATABASE_URL: ""
      LOG_CHANNEL_ID: ""
      ALLOW_OTHER_LINKS: "True"
      MUSIC_CHANNEL_LINK: ""
    deploy:
      resources:
        limits:
          memory: 4000M
