x-uffizzi:
  ingress:
    service: tidaldl
    port: 80
services:
  tidaldl:
    image: tidaldl:latest
    build: .
    environment:
      TG_BOT_TOKEN: ""
      APP_ID: ""
      API_HASH: ""
      AUTH_CHAT: ""
      ADMINS: ""
      ALLOW_DUMP: ""
      SEARCH_CHANNEL: ""
      IS_BOT_PUBLIC: ""
      TIDAL_REGION: "IN"
      BOT_USERNAME: ""
      OWNER_USERNAME: ""
      DATABASE_URL: ""
      LOG_CHANNEL_ID: ""
      ALLOW_OTHER_LINKS: "True"
      MUSIC_CHANNEL_LINK: ""
      WORK_DIR: ""
      DOWNLOADS_FOLDER: ""
      INLINE_THUMB: ""
      TIDAL_SEARCH_LIMIT: ""
      BOT_LANGUAGE: ""
    deploy:
      resources:
        limits:
          memory: 4000M
