x-uffizzi:
  ingress:
    service: app
    port: 8080

services:
  app:
    build: .
    environment:
      TG_BOT_TOKEN: "5617641654:AAEI2pjjFCZuq1EPsRFVXOGAvcafwgKPcOM"
      APP_ID: "1046625"
      API_HASH: "c68afc924b92d73ce27708b155f1e5b4"
      AUTH_CHAT: "-1001201566570"
      ADMINS: "2024984460"
      ALLOW_DUMP: "True"
      SEARCH_CHANNEL: "-1001381073004"
      IS_BOT_PUBLIC: "True"
      TIDAL_REGION: "IN"
      BOT_USERNAME: "@YasirTidalBot"
      OWNER_USERNAME: "@IAmCuteCodes"
      DATABASE_URL: "postgres://qocfhqrl:yTZESrTQVmNO6qccOjSXbJGmVI8OR1lT@lucky.db.elephantsql.com/qocfhqrl"
      LOG_CHANNEL_ID: "-1001381073004"
      ALLOW_OTHER_LINKS: "True"
      MUSIC_CHANNEL_LINK: "https://google.com"
    deploy:
      resources:
        limits:
          memory: 4000M
